<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.15" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ledger.Domain\Ledger.Domain.csproj" />
    <ProjectReference Include="..\Ledger.EventStore\Ledger.EventStore.csproj" />
    <ProjectReference Include="..\Ledger.Projections\Ledger.Projections.csproj" />
  </ItemGroup>

</Project>
